apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter-frontend.fullname" . }}
  labels:
    {{- include "counter-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4200
      nodePort: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP
  selector:
    {{- include "counter-frontend.selectorLabels" . | nindent 4 }}
